<div class="vendor-dashboard-vendcustlist">
	<table>
		<thead>
			<tr>
				<th>Email Id</th>
				<th>Active From</th>
				<th>Status</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>abcdtest@gmail.com</td>
				<td>18/01/2024</td>
				<td>Active</td>
			</tr>
			<tr>
				<td>userdemo@gmail.com</td>
				<td>18/01/2024</td>
				<td>Active</td>
			</tr>
		</tbody>
	</table>
	
	<div class="pagination"><img src="<?php echo $this->getViewFileUrl('images/pagi.jpg'); ?>" alt="" /></div>
</div>