<div class="vendor-dashboard-plan">
	<div class="products wrapper grid products-grid">
		<ol class="products list items product-items">
			<li class="item product product-item active">
				<div class="product-item-info" id="product-item-info_5" data-container="product-grid">
																  
					<span class="product-image-container product-image-container-5" style="width: 240px;">
						<span class="product-image-wrapper" style="padding-bottom: 125%;">
								<img class="product-image-photo" src="<?php echo $this->getViewFileUrl('images/3d-rendering-services_1.jpg'); ?>" loading="lazy" width="240" height="300" alt="Free">
						</span>
					</span>
					   
					<div class="product details product-item-details">
						<strong class="product name product-item-name">Free</strong>
						<div class="price-box price-final_price" data-role="priceBox" data-product-id="5" data-price-box="product-id-5">
							<span class="price-container price-final_price tax weee">
								<span id="product-price-5" data-price-amount="0" data-price-type="finalPrice" class="price-wrapper "><span class="price">$0.00</span></span>
							</span>
						</div>
	
						<div class="product-item-inner">
							<div class="product actions product-item-actions">
								<div data-role="add-to-links" class="actions-secondary"></div>
							</div>
							<div class="product description product-item-description">
								<p>Scale fast with dedicated onboarding, unlimited contacts, and priority support; built for teams.</p>                     
							</div>
							<div class="date-info">
								<div class="start-date">
									<span class="date-label">Start Date</span>
									<span class="date-format">18/01/2024</span>
								</div>
								<div class="end-date">
									<span class="date-label">End Date</span>
									<span class="date-format">20/01/2024</span>
								</div>
							</div>
						</div>
					</div>
				</div>
			</li>
			<li class="item product product-item">
				<div class="product-item-info" id="product-item-info_1" data-container="product-grid">
				
					<span class="product-image-container product-image-container-1" style="width: 240px;">
						<span class="product-image-wrapper" style="padding-bottom: 125%;">
							<img class="product-image-photo" src="<?php echo $this->getViewFileUrl('images/lovepik.jpg'); ?>" loading="lazy" width="240" height="300" alt="Premium">
						</span>
					</span>
					
					<div class="product details product-item-details">
						<strong class="product name product-item-name">Standard</strong>
						<div class="price-box price-final_price" data-role="priceBox" data-product-id="1" data-price-box="product-id-1">
							<span class="special-price">
								<span class="price-container price-final_price tax weee">
									<span class="price-label">Special Price</span>
									<span id="product-price-1" data-price-amount="90" data-price-type="finalPrice" class="price-wrapper "><span class="price">$110.00</span></span>
								</span>
							</span>
							<span class="old-price">
								<span class="price-container price-final_price tax weee">
									<span class="price-label">Regular Price</span>
									<span id="old-price-1" data-price-amount="100" data-price-type="oldPrice" class="price-wrapper "><span class="price">$120.00</span>
									</span>
								</span>
							</span>
						
						</div>
						
						<div class="product-item-inner">
							<div class="product actions product-item-actions">
								  <div data-role="add-to-links" class="actions-secondary"></div>
							  </div>
							<div class="product description product-item-description">
								<p>Scale fast with dedicated onboarding, unlimited contacts, and priority support; built for teams.</p>                                   
							</div>
							
							<div class="actions-primary">
								<form data-role="tocart-form" data-product-sku="Premium" action="#" method="post">
									<button type="submit" title="Subscribe" class="action tocart primary"><span>Upgrade</span></button>
								</form>
							</div>
						
						
						</div>
					</div>
				</div>
			</li>                  
			<li class="item product product-item">
				<div class="product-item-info" id="product-item-info_1" data-container="product-grid">
				
					<span class="product-image-container product-image-container-1" style="width: 240px;">
						<span class="product-image-wrapper" style="padding-bottom: 125%;">
							<img class="product-image-photo" src="<?php echo $this->getViewFileUrl('images/lovepik.jpg'); ?>" loading="lazy" width="240" height="300" alt="Premium">
						</span>
					</span>
					
					<div class="product details product-item-details">
						<strong class="product name product-item-name">Essentials</strong>
						<div class="price-box price-final_price" data-role="priceBox" data-product-id="1" data-price-box="product-id-1">
							<span class="special-price">
								<span class="price-container price-final_price tax weee">
									<span class="price-label">Special Price</span>
									<span id="product-price-1" data-price-amount="90" data-price-type="finalPrice" class="price-wrapper "><span class="price">$120.00</span></span>
								</span>
							</span>
							<span class="old-price">
								<span class="price-container price-final_price tax weee">
									<span class="price-label">Regular Price</span>
									<span id="old-price-1" data-price-amount="100" data-price-type="oldPrice" class="price-wrapper "><span class="price">$150.00</span>
									</span>
								</span>
							</span>
						
						</div>
						
						<div class="product-item-inner">
							<div class="product actions product-item-actions">
								  <div data-role="add-to-links" class="actions-secondary"></div>
							  </div>
							<div class="product description product-item-description">
								<p>Scale fast with dedicated onboarding, unlimited contacts, and priority support; built for teams.</p>                                   
							</div>
							
							<div class="actions-primary">
								<form data-role="tocart-form" data-product-sku="Premium" action="#" method="post">
									<button type="submit" title="Subscribe" class="action tocart primary"><span>Upgrade</span></button>
								</form>
							</div>
						
						
						</div>
					</div>
				</div>
			</li>
			<li class="item product product-item">
				<div class="product-item-info" id="product-item-info_1" data-container="product-grid">
				
					<span class="product-image-container product-image-container-1" style="width: 240px;">
						<span class="product-image-wrapper" style="padding-bottom: 125%;">
							<img class="product-image-photo" src="<?php echo $this->getViewFileUrl('images/lovepik.jpg'); ?>" loading="lazy" width="240" height="300" alt="Premium">
						</span>
					</span>
					
					<div class="product details product-item-details">
						<strong class="product name product-item-name">Premium</strong>
						<div class="price-box price-final_price" data-role="priceBox" data-product-id="1" data-price-box="product-id-1">
							<span class="special-price">
								<span class="price-container price-final_price tax weee">
									<span class="price-label">Special Price</span>
									<span id="product-price-1" data-price-amount="90" data-price-type="finalPrice" class="price-wrapper "><span class="price">$90.00</span></span>
								</span>
							</span>
							<span class="old-price">
								<span class="price-container price-final_price tax weee">
									<span class="price-label">Regular Price</span>
									<span id="old-price-1" data-price-amount="100" data-price-type="oldPrice" class="price-wrapper "><span class="price">$100.00</span>
									</span>
								</span>
							</span>
						
						</div>
						
						<div class="product-item-inner">
							<div class="product actions product-item-actions">
								  <div data-role="add-to-links" class="actions-secondary"></div>
							  </div>
							<div class="product description product-item-description">
								<p>Scale fast with dedicated onboarding, unlimited contacts, and priority support; built for teams.</p>                                   
							</div>
							
							<div class="actions-primary">
								<form data-role="tocart-form" data-product-sku="Premium" action="#" method="post">
									<button type="submit" title="Subscribe" class="action tocart primary"><span>Upgrade</span></button>
								</form>
							</div>
						
						
						</div>
					</div>
				</div>
			</li>
		</ol>
	</div>
</div>