<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Custom Form Base for Magento 2
 */
/**
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Amasty\Customform\ViewModel\Export\Pdf\SubmittedData\Fields\DefaultField $viewModel
 */
$viewModel = $block->getViewModel();
?>

<?= $escaper->escapeHtml($viewModel->getFieldValue()) ?>
