<div class="vendor-dashboard-vendcustlist">
	<table>
		<thead>
			<tr>
				<th>Website</th>
				<th>Date</th>
				<th>Status</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>testwebsiteurl.com</td>
				<td>18/01/2024</td>
				<td><a href="#">Unauthorised</a></td>
			</tr>
			<tr>
				<td>testwebsiteurl.co.nz</td>
				<td>18/01/2024</td>
				<td><a href="#">Authorised</a></td>
			</tr>
		</tbody>
	</table>
	
	<div class="pagination"><img src="<?php echo $this->getViewFileUrl('images/pagi.jpg'); ?>" alt="" /></div>
</div>