<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package App for Payments with Stripe for Magento 2
 */ /** @var Amasty\Stripe\Block\Customer\SavedCards $block */ ?>
<div data-bind="scope: 'amasty-stripe-saved-cards'" class="amstripe-saved-cards">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": <?php /** @escapeNotVerified */ echo $block->getJsLayout();?>
            }
        }
    </script>
</div>
