<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Custom Form Base for Magento 2
 */
/**
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Amasty\Customform\ViewModel\Answser\AnswerIndex $viewModel
 */

$viewModel = $block->getViewModel();
?>

<section class="amcform-table-wrap">
    <h3 class="amcform-title">
        <?= /* @noEscape */ __('Admin Response') ?>
    </h3>
    <div class="amcform-content">
        <table class="amcform-table-block">
            <?php foreach ($viewModel->getAdminResponseData() as $data): ?>
                <tr class="amcform-tr">
                    <th class="amcform-th"><?= $escaper->escapeHtml($data['label']) ?></th>
                    <td class="amcform-td"><?= /* @noEscape */ $data['value']?></td>
                </tr>
            <?php endforeach;?>
        </table>
    </div>
</section>
