<?php  //$block \Blink\Customerapi\Block\Login ?>

<?php $data= $block->getCustomdata();

 // print_r($data);
?>
<div class="custom-login">
    <form class="form login" action="https://stage.blinksignup.com/customerapi/account/datasend/" method="post" id="myForm">
      
      <?php if(!$data['ref']) : ?>
      
        <p> Hi, <?=$data['name'] ?> this is an Unauthorized website . Please close window </p>
       
      <?php else :?>  
      
      <p> Hi, <?=$data['name'] ?> You are going to share your data with <?=$data['ref']?></p>
        <button id="conf">Confirm</button>
         <button id="can">Cancel</button>
      
      <?php endif ?>
       
     
        
       
       <input type="hidden" name="authvalue" value="1">
       
    </form>
    
</div>

<script>
// Automatically submit the form when the window loads
window.onload = function() {
  var form = document.getElementById('myForm');
  
  
  document.getElementById("conf").addEventListener("click", function () {
  form.submit();
 // setTimeout(function() {window.close();}, 5000);
 // window.close();
});
  
   document.getElementById("can").addEventListener("click", function () {

  setTimeout(function() {window.close();}, 1000);
 // window.close();
});
  
  
  
  // Close the popup after a delay (adjust the delay as needed)

};
</script>