<div class="home-toptitle">
	<div class="custom-inner-container">
		<div class="circles">
			<div class="circle1"></div>
			<div class="circle2"></div>
			<div class="circle3"></div>
		</div>
		<h1><span>Blink</span> And You're In.</h1>
		<a href="<?php echo $this->getUrl('customer/account/create') ?>" class="btn-large action primary">Sign Up for Free</a>
	</div>
</div>

<div class="ocean-outer">
	<!--<div class="ocean">
	  <div class="wave"></div>
	  <div class="wave"></div>
	</div>
	<div class="ocean down">
	  <div class="wave"></div>
	  <div class="wave"></div>
	</div>-->
	
	<div class="custom-inner-container">
		<div class="oneclick-left">
			<h2>One Click To Create An Account. One Click to Log In.</h2>
			<p>With a single Blink account, shoppers will be able to create account and log in with one click anywhere they see a Blink button. No more questionnaires, text and email verifications, or password recoveries.</p>
		</div>
		<div class="oneclick-right" data-aos="fade-up">
			<img src="<?php echo $this->getViewFileUrl('images/laptop.png'); ?>" alt="Blink Easy Shopping" />
			<div class="logo-in-lap">
				<img src="<?php echo $this->getViewFileUrl('images/logo-in-lap.png'); ?>" alt="Blink Easy Shopping" />
			</div>
		</div>
	</div>
</div>


			

<div class="onescan-outer">
	<div class="custom-inner-container">
		<div class="onescan-left" data-aos="zoom-in" data-aos-duration="3000">
			<!--<img src="<?php echo $this->getViewFileUrl('images/smartphone.png'); ?>" alt="Blink Easy Shopping" />-->
			<script src="https://unpkg.com/@dotlottie/player-component@latest/dist/dotlottie-player.mjs" type="module"></script> 

    <dotlottie-player src="https://lottie.host/187c938a-c0a1-4e80-ae49-89ff448a68a1/WAJLLAPAGQ.json" background="transparent" speed="1" style="width: 700px; height: 700px; margin-left: -100px; margin-top: 70px; transform: rotate(-20deg);" loop autoplay></dotlottie-player>
		</div>
		<div class="onescan-right" data-aos="zoom-out">
			<h2>One Scan To Create An Account. One Click to Log In.</h2>
			<div class="roundbox-text">
				<span class="roundbox-shape"></span>
				<p>With a simple scan of a retailer's unique Blink QR code, shoppers will be able to create an account instantly in-store. No more reciting email addressed or beckoning shoppers to fill out an online form to create an account.</p>
	
				<p>Returning Blink account shoppers can also scan their unique Blink QR code at checkout to instantly log in to their customer account. Earning and using loyalty rewards, tracking purchage history, and accessing digital	receipts is no longer online-only.</p>
				
				<a href="<?php echo $this->getUrl('customer/account/create') ?>" class="btn-large action primary">Sign Up for Free</a>
			</div>
		</div>
	</div>
	<div class="side-roundbox-shape left-side" data-aos="fade-right">
		<span class="left"></span>
	</div>
	<div class="side-roundbox-shape right-side" data-aos="fade-left">
		<span class="right"></span>
	</div>
</div>

<div class="nomore-interruption">
	<h2 data-aos="fade-right">No More</h2>
	<h3 data-aos="fade-left">Interruptions</h3>
	<div class="custom-inner-container">
		<div class="popup1" data-aos="zoom-out">
			<img src="<?php echo $this->getViewFileUrl('images/popup1.png'); ?>" alt="Blink Easy Shopping" />
		</div>
		<div class="popup2" data-aos="zoom-in">
			<img src="<?php echo $this->getViewFileUrl('images/popup2.png'); ?>" alt="Blink Easy Shopping" />
		</div>
		<div class="popup3" data-aos="fade-up">
			<img src="<?php echo $this->getViewFileUrl('images/popup3.png'); ?>" alt="Blink Easy Shopping" />
		</div>
		<div class="popup4" data-aos="fade-right">
			<img src="<?php echo $this->getViewFileUrl('images/popup4.png'); ?>" alt="Blink Easy Shopping" />
		</div>
		<div class="popup5" data-aos="fade-down">
			<img src="<?php echo $this->getViewFileUrl('images/popup5.png'); ?>" alt="Blink Easy Shopping" />
		</div>
	</div>
	<span class="circle1" data-aos="zoom-out" data-aos-duration="3000"></span>
	<span class="circle2" data-aos="zoom-in" data-aos-duration="3000"></span>
	<span class="circle3" data-aos="fade-up" data-aos-duration="3000"></span>
</div>


<div class="email-protection">
	<h2>Email Protection & Privacy</h2>
	<div class="custom-inner-container">
		<div class="email-protect-left" data-aos="fade-left">
			<img src="<?php echo $this->getViewFileUrl('images/email.png'); ?>" alt="Blink Easy Shopping" />
		</div>
		<div class="email-protect-right" data-aos="fade-right">
			<p>Blink does not use personal emails or passwords to sign up or log in, but rather a unique ID for each business that you've linked through Blink. If one business has a data breach, your customer account cannot be traced back to an email address or pass that might've been used on many other online accounts.</p>

			<p>Because Blink signups and logins do not require a personal email, your inbox will no longer be filled with spam. Instead, your Blink profile allows full customization on what type of emails and from what businesses are authorized to be pushed to your personal email inbox.</p>
		</div>
	</div>
</div>



<script type="text/javascript">
requirejs( [ 'require', 'jquery',  'aosLib' ],
function( require, $, AOS ) {
         AOS.init({
                  duration: 1500,
         });

});
</script>
