<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Customer Attributes Base for Magento 2
 */
/** @var $block \Amasty\CustomerAttributes\Block\Adminhtml\Customer\Attribute\Edit\Tab\Options\Options */
$values = [];
foreach ($block->getOptionValues() as $value) {
    $value = $value->getData();
    $values[] = is_array($value) ? array_map(function ($str) {
        return htmlspecialchars_decode($str, ENT_QUOTES);
    }, $value) : $value;
}
?>
<fieldset class="fieldset">
    <legend class="legend">
        <span><?= $block->escapeHtml(__('Manage Options (values of your attribute)')) ?></span>
    </legend>
    <div id="manage-options-panel" class="selected-type-options">
        <div id="save-page-message" style="font-weight: 600; margin: 10px;">
            <?= $block->escapeHtml(__('Note. Please save attribute for uploading images.')) ?>
        </div>
        <div id="new-selectgroup-message" style="font-weight: 600; margin: 10px; display: none;">
            <?= $block->escapeHtml(__('Please save the attribute to set the `Customer Group Selector` options')) ?>
        </div>
        <table class="admin__control-table ">
            <thead>
                <tr id="attribute-options-table">
                    <th class="col-draggable"></th>
                    <th class="col-default control-table-actions-th"><?= $block->escapeHtml(__('Is Default')) ?></th>
                    <?php $storeList = $block->getStoresSortedBySortOrder(); ?>
                    <?php foreach ($storeList as $store): ?>
                        <th<?= ($store->getId() == \Magento\Store\Model\Store::DEFAULT_STORE_ID)?' class="_required"':''; ?>>
                            <span><?= $block->escapeHtml(__($store->getName())); ?></span>
                        </th>
                    <?php endforeach; ?>
                    <?php $storeTotal = count($storeList) + 3; ?>
                    <?php if ($block->isUseImages()): ?>
                        <?php $storeTotal += 2; ?>
                        <th class="col-default type-image-icon"><?= $block->escapeHtml(__('Icon Image')) ?></th>
                        <th class="col-default type-image-icon"><?= $block->escapeHtml(__('Remove Icon Image')) ?></th>
                    <?php endif; ?>
                    <th class="col-delete">&nbsp;</th>
                </tr>
            </thead>
            <tbody data-role="options-container" class="ignore-validate"></tbody>
            <tfoot>
                <tr>
                    <th colspan="<?= /* @noEscape */ (int) $storeTotal ?>" class="validation">
                        <input type="hidden" class="required-dropdown-attribute-entry" name="dropdown_attribute_validation" />
                    </th>
                </tr>
                <tr>
                    <th colspan="<?= /* @noEscape */ (int) $storeTotal; ?>" class="col-actions-add">
                        <?php if (!$block->getReadOnly() && !$block->canManageOptionDefaultOnly()): ?>
                            <button id="add_new_option_button" title="<?= $block->escapeHtml(__('Add Option')) ?>" type="button" class="action- scalable add">
                                <span><?= $block->escapeHtml(__('Add Option')) ?></span>
                            </button>
                        <?php endif; ?>
                    </th>
                </tr>
            </tfoot>
        </table>
        <input type="hidden" id="option-count-check" value="" />
    </div>
    <script id="row-template" type="text/x-magento-template">
        <tr>
            <td class="col-draggable">
                <?php if (!$block->getReadOnly() && !$block->canManageOptionDefaultOnly()): ?>
                    <div data-role="draggable-handle" class="draggable-handle" title="<?= $block->escapeHtml(__('Sort Option')) ?>"></div>
                <?php endif; ?>
                <input data-role="order" type="hidden" name="option[order][<%- data.id %>]" value="<%- data.sort_order %>"
                    <?php if ($block->getReadOnly() || $block->canManageOptionDefaultOnly()): ?>
                        disabled="disabled"
                    <?php endif; ?>
                />
            </td>
            <td class="col-default control-table-actions-cell">
                <input class="input-radio" type="<%- data.intype %>" name="default[]" value="<%- data.id %>" <%- data.checked %>
                    <?php if ($block->getReadOnly()): ?>
                        disabled="disabled"
                    <?php endif; ?>
                />
            </td>
            <?php foreach ($storeList as $store): ?>
                <td class="col-<%- data.id %>">
                    <input
                        name="option[value][<%- data.id %>][<?= $block->escapeHtml($store->getId()) ?>]"
                        value="<%- data.store<?= $block->escapeHtml($store->getId()); ?> %>"
                        class="input-text
                        <?php if ($store->getId() == \Magento\Store\Model\Store::DEFAULT_STORE_ID): ?>
                            required-option
                        <?php endif; ?>"
                        type="text"
                        <?php if ($block->getReadOnly() || $block->canManageOptionDefaultOnly()): ?>
                            disabled="disabled"
                        <?php endif; ?>
                    />
                </td>
            <?php endforeach; ?>
            <?php if ($block->isUseImages()): ?>
                <td class="type-image-icon" align="center" <% if (!window.iconColumnVisibility) { %>style="display: none;"<% } %>>
                    <img src="<%- data.icon%>" alt="<?= $block->escapeHtml(__('[no-image]')) ?>" style="max-width: 250px;">
                    <input type="file" name="amcustomerattr_icon[<%- data.id %>]">
                </td>
                <td class="type-image-icon" align="center" <% if (!window.iconColumnVisibility) { %>style="display: none;"<% } %>>
                    <input type="checkbox" value="1" name="amcustomerattr_icon_delete[<%- data.id %>]">
                </td>
            <?php endif; ?>
            <td id="delete_button_container_<%- data.id %>" class="col-delete">
                <input type="hidden" class="delete-flag" name="option[delete][<%- data.id %>]" value=""/>
                <?php if (!$block->getReadOnly() && !$block->canManageOptionDefaultOnly()): ?>
                    <button id="delete_button_<%- data.id %>" title="<?= $block->escapeHtml(__('Delete')) ?>" type="button" class="action- scalable delete delete-option">
                        <span><?= $block->escapeHtml(__('Delete')) ?></span>
                    </button>
                <?php endif; ?>
            </td>
        </tr>
    </script>
    <?php if ($block->isUseImages()): ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "Amasty_CustomerAttributes/js/filesupload": {
                    "baseUrl": "<?= $block->escapeUrl($block->getUrl('amcustomerattr/load/load')) ?>",
                    "form_key": "<?= $block->escapeHtml($block->getFormKey()) ?>"
                }
            }
        }
    </script>
    <?php endif; ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Catalog/js/options": {
                    "attributesData": <?= /* @noEscape */ json_encode($values, JSON_HEX_QUOT) ?>,
                    "isSortable":  <?= /* @noEscape */ (int) (!$block->getReadOnly() && !$block->canManageOptionDefaultOnly()) ?>,
                    "isReadOnly": <?= /* @noEscape */ (int) $block->getReadOnly() ?>
                }
            }
        }
    </script>
    <script>
        require([
            'jquery',
            'domReady!'
        ], function ($) {
            $('#edit_form').attr('enctype', 'multipart/form-data');

            function bindIsDefaultRadioButtons() {
                jQuery('input[name="default[]"]').each(function (ch, item) {
                    jQuery(item).click(function () {
                        elem = jQuery(this);

                        if (elem.attr('previousValue') == 'checked') {
                            elem.attr('checked', false);
                            elem.attr('previousValue', false);
                        } else {
                            jQuery('input[name="default[]"]').attr('previousValue', false);
                        }

                        elem.attr('previousValue', elem.attr('checked'));
                    });
                })
            }

            setTimeout(function () {
                bindIsDefaultRadioButtons();
            }, 2000);

        });
    </script>
</fieldset>
